spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bigdata
    username: caesar
    password: 164375
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8022

